### ISSUE TITLE
Ergebnisanzeige

### ISSUE THREAD

**Issue by BBeulmann** [RabeaMue/Bdk-Library_Carpentry_Aufgabenset_1_Rabea_Mueller#1]
Hallo Rabea,
eventuell könntest Du bei der Ergebnisausgabe noch klarstellen, welche Angaben genau vorliegen.
Z.B.: Titel: .... Jahr: ....
Ansonsten alles top!

Gruß
Björn

**Comment by BBeulmann** [comment]
Zu finden bei Dir unter in[13]+[15]: 

Molegro Virtual Docker for Docking.(2019)

**Comment by RabeaMue** [comment]
Hallo Björn, danke für den Tipp. Habe es ergänzt! :)
