### ISSUE TITLE
Tabellengröße

### ISSUE THREAD

**Issue by BBeulmann** [RabeaMue/Bdk-Library_Carpentry_Aufgabenset_1_Rabea_Mueller#4]
Hallo Rabea!
Ich habe mir Dein Script angesehen und finde es mal wieder hervorragend.
Um ehrlich zu sein, sprengt das Ganze latent meinen Kompetenzrahmen.
Von daher weiß ich gerade nicht, ob mein Issue ungewollt unverschämt ist und unverhältnismäßig hohen Mehraufwand bedeutet.
Ich trau mich aber dennoch mal:
Ich würde bei den Tabellen zur Fragestellung die Informationsdichte reduzieren, d.h. weniger Columns ausgeben lassen. Vielleicht erst einmal so, dass man den Balken zum Scrollen nicht mehr benötigt.
Z.B. sind die Spalten "Notice Preference Code", "Notice Preference Definition", und "Provided Email Adress" im Verhältnis zu den Fragestellungen nicht erforderlich.

LG
Björn

**Comment by RabeaMue** [comment]
Hallo Björn,

eine gute Idee für eine bessere Übersicht.
LG Rabea
